stages:
  prepare:
    cmd: python data_loader.py
    deps:
      - data_loader.py
    outs:
      - data/ 

  train:
    cmd: python train_model.py
    deps:
      - train_model.py
      - data/
    outs:
      - mlruns/